naam = input("Vul je naam in: ")
adres = input("Vul je adres in: ")
postcode = input("Vul je postcode in: ")
woonplaats = input("Vul je woonplaats in: ")

print("---------------------------------------------------- ")
print("|  Naam      : " + naam)
print("|  Adres     : " + adres)
print("|  Postcode  : " + postcode)
print("|  Woonplaats: " + woonplaats)
print(" ----------------------------------------------------")